name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT}}
          script: |
            set -e

            docker stop hw-food || true
            docker rm hw-food || true

            cd ~/hw-food-bot
            git pull origin main

            echo "${{ secrets.ENV_FILE }}" > .env

            docker build . -t hw-food
            docker run -d \
              --name hw-food-bot \
              --restart unless-stopped \
              --env-file ~/hw-food-bot/.env \
              hw-food

            docker image prune -f
